Repository MoimPod/moimpod, pull requests merged in 2025-02, with the labels that each got.

#18 ESLint와 husky 재설정
  .eslintignore
  .eslintrc.js
  .husky/pre-commit
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
Labels: bug

#26 Feature/공용 버튼 컴포넌트
  src/components/Button.tsx
  src/components/Spinner.tsx
  src/utils/classnames.ts
Labels: enhancement

#128 progress bar, 참여인원 animation 구현
  package-lock.json
  package.json
  src/components/AnimateParticipantCount.tsx
  src/components/Card.tsx
  src/components/ProgressBar.tsx
Labels: 기능

#130 feat: 모임에 관한 인터렉션 구현
  src/app/(common)/gathering/[id]/page.tsx
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/app/(common)/gathering/_hooks/useCancelGathering.ts
  src/app/(common)/gathering/_hooks/useGetParticipants.ts
  src/app/(common)/gathering/_hooks/useGetReviews.ts
  src/app/(common)/gathering/_hooks/useJoin.ts
  src/app/(common)/gathering/_hooks/useLeaveGathering.ts
  src/app/(common)/gathering/_utils/apis.ts
  src/components/LoginModal.tsx
  src/components/Modal.tsx
  src/utils/copyClipboard.ts
Labels: 기능

#137 / 페이지 위치 변경
  src/app/(common)/page.tsx
  src/app/page.tsx
Labels: 페이지

#134 feat: pop-up
  src/app/(common)/gathering/[id]/page.tsx
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/components/Button.tsx
  src/components/LoginModal.tsx
  src/components/Popup/LoginPopup.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/index.ts
Labels: 기능, UI, 공용 컴포넌트

#138 layout 밑 여백 제거
  src/app/(common)/layout.tsx
  src/app/layout.tsx
Labels: UI, 페이지

#135 feat: 찜한 모임 페이지 생성
  public/images/favorites_logo.svg
  src/app/(common)/_home/CardList.tsx
  src/app/(common)/_home/_components/ServiceTab.tsx
  src/app/(common)/_home/_hooks/useFetchGatherings.ts
  src/app/(common)/favorites/page.tsx
  src/components/Card.tsx
Labels: 기능, UI, 페이지

#140 Fix: infinite scroll Hook 분리
  src/app/(common)/_home/CardList.tsx
  src/app/(common)/favorites/page.tsx
  src/hooks/useInfiniteScroll.ts
Labels: 기능

#139 마이페이지 - 나의 모임 구현
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileEditModal.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileHeader.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileInfo.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileSection.tsx
  src/app/(common)/mypage/_components/ProfileSection/index.ts
  src/app/(common)/mypage/_components/ReviewModal.tsx
  src/app/(common)/mypage/_hooks/useGetJoinedGatherings.ts
  src/app/(common)/mypage/_hooks/usePostReviews.ts
  src/app/(common)/mypage/page.tsx
  src/components/InactiveLayer.tsx
  src/components/ListItem.tsx
  src/components/MypageContent.tsx
  src/hooks/useLeaveGathering.ts
Labels: 기능, UI, 페이지

#146 Feat: login check 후 모임 만들기 모달 열기
  src/app/(auth)/sign-in/page.tsx
  src/app/(common)/_home/CardList.tsx
  src/app/(common)/_home/_hooks/useCheckAuth.ts
  src/app/(common)/_home/_hooks/useFetchGatherings.ts
  src/app/(common)/page.tsx
  src/stores/useUserStore.ts
Labels: 기능, 페이지

#147 마이페이지 - 내가 작성한 리뷰 구현
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MyReviews.tsx
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_components/ReviewableGatherings.tsx
  src/app/(common)/mypage/_hooks/useGetMyReviews.ts
  src/app/(common)/mypage/_hooks/usePostReviews.ts
  src/components/Header.tsx
  src/components/ListItem.tsx
Labels: 기능, UI, 페이지

#148 fix: sort button 재사용 컴포넌트
  src/app/(common)/_home/_components/GatheringFilters.tsx
  src/components/SortButton.tsx
Labels: 공용 컴포넌트

#154 fix: 글로벌 색상 변수 지정
  src/components/Button.tsx
  tailwind.config.ts
Labels: 문서, 공용 컴포넌트

#151 Fix: location roll back
  src/app/(common)/_home/_components/CreateGatheringsModal.tsx
  src/app/(common)/_home/_components/GatheringFilters.tsx
  src/components/Dropdown.tsx
  src/components/Filtering/DateSelect.tsx
  src/components/Filtering/LocationSelect.tsx
Labels: UI

#157 마이페이지 - 내가 만든 모임 구현
  src/app/(common)/mypage/_components/MyCreatedGatherings.tsx
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_hooks/useGetCreatedGathering.ts
Labels: 기능, UI, 페이지

#158 마이페이지 - 컬러 변경
  public/images/profile_background.svg
  src/app/(common)/mypage/_components/ProfileSection/ProfileHeader.tsx
  src/components/LikeButton.tsx
  src/components/ListItem.tsx
Labels: UI

#153 fix: sort button 외부 클릭 시 드롭다운 닫힘, ux 개선, style 수정
  src/app/(common)/_home/_components/CreateGatheringsModal.tsx
  src/components/Dropdown.tsx
  src/components/SortButton.tsx
Labels: UI

#160 Feat: 모임 만들기 모달에서 모임 생성 가능
  public/images/default_image.png
  src/app/(common)/_home/_components/CreateGatheringsModal.tsx
  src/app/(common)/_home/_hooks/useCreateGathering.ts
  src/components/Card.tsx
  src/components/CategoryButton.tsx
  src/components/ChipInfo.tsx
  src/components/Filtering/CustomTimepicker.tsx
  src/components/Filtering/DateSelect.tsx
  src/stores/useGatheringStore.ts
Labels: 기능

#161 fix: 참여 인터랙션에 따른 UI 변경
  src/app/(common)/gathering/[id]/page.tsx
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/app/(common)/gathering/_components/GatheredProfiles.tsx
  src/app/(common)/gathering/_components/Gathering.tsx
  src/app/(common)/gathering/_components/GatheringInfo.tsx
  src/app/(common)/gathering/_components/ReviewList.tsx
  src/app/(common)/gathering/_components/Reviews.tsx
  src/app/(common)/gathering/_hooks/useGetParticipants.ts
  src/app/(common)/gathering/_hooks/useGetReviews.ts
  src/app/(common)/gathering/_hooks/useJoin.ts
  src/app/(common)/gathering/_utils/apis.ts
  src/app/(common)/gathering/_utils/constants.ts
  src/app/(common)/gathering/_utils/queryUtils.ts
  src/app/(common)/gathering/types.ts
  src/components/DashedLine.tsx
  src/hooks/useQueryParams.ts
  src/lib/getQueryClient.ts
Labels: 기능, 페이지

#163 마이페이지 - 수정사항(쿼리 키 재설정 및 유저정보 로직 수정 등)
  public/images/bye.svg
  src/app/(common)/mypage/_components/MyCreatedGatherings.tsx
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MyReviews.tsx
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileEditModal.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileHeader.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileSection.tsx
  src/app/(common)/mypage/_components/ReviewableGatherings.tsx
  src/app/(common)/mypage/_hooks/useGetCreatedGathering.ts
  src/app/(common)/mypage/_hooks/useGetMyGatherings.ts
  src/app/(common)/mypage/_hooks/useGetMyReviews.ts
  src/app/(common)/mypage/_hooks/useGetUserInfo.ts
  src/app/(common)/mypage/_hooks/usePostReviews.ts
  src/app/(common)/mypage/_hooks/useUpdateUserInfo.ts
  src/app/(common)/mypage/types.ts
  src/components/InactiveLayer.tsx
  src/components/ListItem.tsx
Labels: 기능, UI, 페이지

#164 Fix: 필터링 기능 구현
  src/app/(common)/_home/CardList.tsx
  src/app/(common)/_home/_components/CreateGatheringsModal.tsx
  src/app/(common)/_home/_components/GatheringFilters.tsx
  src/app/(common)/_home/_components/ServiceTab.tsx
  src/app/(common)/_home/_hooks/useFetchGatherings.ts
  src/app/(common)/favorites/page.tsx
  src/app/(common)/page.tsx
  src/components/Card.tsx
  src/components/CategoryButton.tsx
  src/components/Dropdown.tsx
  src/components/Filtering/DateSelect.tsx
  src/components/Filtering/LocationSelect.tsx
  src/stores/useGatheringStore.ts
Labels: 기능

#169 마이페이지 - 리팩터링(무한스크롤 제거, MyPageList 컴포넌트)
  src/app/(common)/mypage/_components/MyCreatedGatherings.tsx
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MyReviews.tsx
  src/app/(common)/mypage/_components/MypageList.tsx
  src/app/(common)/mypage/_components/ReviewableGatherings.tsx
  src/app/(common)/mypage/_hooks/useGetCreatedGathering.ts
  src/app/(common)/mypage/_hooks/useGetMyGatherings.ts
  src/app/(common)/mypage/_hooks/useGetMyReviews.ts
  src/app/(common)/mypage/types.ts
  src/app/(common)/mypage/utils/apis.ts
Labels: 기능, 리팩토링

#172 마이페이지 - 리팩토링(기본 이미지 설정, day.js적용, 유효성 검사 적용)
  src/app/(common)/mypage/_components/MyCreatedGatherings.tsx
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MyReviews.tsx
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileEditModal.tsx
  src/app/(common)/mypage/_components/ReviewModal.tsx
  src/app/(common)/mypage/_components/ReviewableGatherings.tsx
  src/app/(common)/mypage/utils/apis.ts
  src/components/ListItem.tsx
  src/utils/formatDateToYYYYMMDD.ts
Labels: 기능, 리팩토링

#173 LikeButton 및 Score 컴포넌트 스타일 기능 추가
  src/components/LikeButton.tsx
  src/components/Score.tsx
Labels: 기능

#174 마이페이지 - 스켈레톤 적용 및 캐싱 데이터 사용
  src/app/(common)/mypage/_components/ProfileSection/ProfileEditModal.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileInfo.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileSection.tsx
Labels: UI, 리팩토링

#176 fix: 모든 리뷰, 상세 페이지 수정
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/app/(common)/gathering/_components/Gathering.tsx
  src/app/(common)/gathering/_components/GatheringInfo.tsx
  src/app/(common)/gathering/_components/Thumbnail.tsx
  src/app/(common)/reviews/page.tsx
  src/utils/copyClipboard.ts
Labels: 리팩토링

#178 fix: 모집 정원 5명에서 멈추는 버그 수정
  src/app/(common)/gathering/[id]/page.tsx
  src/app/(common)/gathering/_utils/apis.ts
Labels: 버그

#179 마이페이지 - 리팩터링 및 수정 (컴포넌트 분리, 작성 가능한 리뷰 수정, ListItem날짜 수정)
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_components/ProfileSection/index.ts
  src/app/(common)/mypage/_components/ReviewModal.tsx
  src/app/(common)/mypage/_components/ReviewModal/CommentInput.tsx
  src/app/(common)/mypage/_components/ReviewModal/FormActions.tsx
  src/app/(common)/mypage/_components/ReviewModal/RatingInput.tsx
  src/app/(common)/mypage/_components/ReviewModal/ReviewModal.tsx
  src/app/(common)/mypage/_components/ReviewModal/index.ts
  src/app/(common)/mypage/_components/ReviewableGatherings.tsx
  src/app/(common)/mypage/_hooks/useMypageTab.ts
  src/app/(common)/mypage/_hooks/useReviewForm.ts
  src/app/(common)/mypage/page.tsx
  src/app/(common)/mypage/utils/apis.ts
  src/components/ListItem.tsx
Labels: 버그, 리팩토링

#182 마이페이지 - InactiveLayer 수정 및 ListItem시간 수정
  src/app/(common)/mypage/_hooks/useReviewForm.ts
  src/components/InactiveLayer.tsx
  src/components/ListItem.tsx
Labels: UI
