Repository MoimPod/moimpod, pull requests merged in 2025-03, with the labels that each got.

#187 마이페이지 - prefetch 적용
  src/app/(common)/mypage/_components/ProfileSection/ProfileInfo.tsx
  src/app/(common)/mypage/page.tsx
Labels: 페이지, 리팩토링

#193 body 기본 color 삭제
  src/app/globals.css
Labels: UI

#195 마이페이지 - 타입 수정
  src/app/(common)/mypage/_components/MypageList.tsx
  src/app/(common)/mypage/_hooks/useGetUserInfo.ts
  src/app/(common)/mypage/page.tsx
  src/app/(common)/mypage/types.ts
  src/app/(common)/mypage/utils/apis.ts
Labels: 리팩토링

#196 마이페이지 - 프로필 수정 모달 리팩토링
  src/app/(common)/mypage/_components/ProfileSection/ProfileEditModal.tsx
  src/app/(common)/mypage/_hooks/useProfileEditForm.ts
Labels: 기능, 리팩토링

#199 Scroll To Top 버튼 구현
  src/app/(common)/layout.tsx
  src/components/ScrollToTop.tsx
  tailwind.config.ts
Labels: 기능, UI

#203 마이페이지에서 모임 항목을 누르면 모임 상세 페이지로 이동
  src/app/(common)/mypage/_components/MyCreatedGatherings.tsx
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MyReviews.tsx
  src/app/(common)/mypage/_components/ReviewableGatherings.tsx
Labels: 기능

#206 fix: error fallback UI
  src/app/(common)/error.tsx
  src/app/(common)/gathering/error.tsx
  src/components/ErrorBoundary.tsx
Labels: UI

#205 fix: 마이 페이지를 SuspenseQuery 변경 #202
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_components/MypageList.tsx
Labels: 리팩토링

#208 fix: 프로필 이미지 hover animation
  src/app/(common)/gathering/_components/GatheredProfiles.tsx
Labels: 기능

#209 마이페이지 - 프리 페칭 수정
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/MyReviews.tsx
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/page.tsx
Labels: 리팩토링

#214 마이페이지 - 프로필 정보 수정 로딩 및 에러 핸들링
  src/app/(common)/mypage/_components/ProfileSection/ProfileEditModal.tsx
  src/app/(common)/mypage/_hooks/useProfileEditForm.ts
  src/app/(common)/mypage/_hooks/useUpdateUserInfo.ts
Labels: 기능

#216 fix: 날짜 utc 기준으로 변경
  src/app/(common)/_home/_components/CreateGatheringsModal.tsx
  src/components/ChipInfo.tsx
Labels: 버그

#218 마이 페이지 - 시간 utc설정 및 프리페칭 로직 수정
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/components/ListItem.tsx
Labels: 기능, 리팩토링

#220 fix: 모든리뷰 레이아웃 css 수정
  src/app/(common)/reviews/page.tsx
Labels: 리팩토링

#221 fix: 타입정리
  src/app/(common)/_home/_hooks/useFetchGatherings.ts
  src/app/(common)/favorites/FavoriteList.tsx
  src/app/(common)/gathering/[id]/page.tsx
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/app/(common)/gathering/_components/Gathering.tsx
  src/app/(common)/gathering/_components/GatheringInfo.tsx
  src/app/(common)/gathering/_components/Reviews.tsx
  src/app/(common)/gathering/_utils/apis.ts
  src/app/(common)/gathering/types.ts
  src/app/(common)/reviews/_components/AllReview.tsx
  src/app/(common)/reviews/page.tsx
  src/components/Card.tsx
  src/hooks/useQueryParams.ts
  src/types.ts
Labels: 버그, 리팩토링

#223 마이페이지 - 나의 모임 동작(리뷰, 취소) 의 로딩 및 에러 핸들링
  src/app/(common)/mypage/_components/CancelConfirmModal.tsx
  src/app/(common)/mypage/_components/MyGatherings.tsx
  src/app/(common)/mypage/_components/ProfileSection/ProfileEditModal.tsx
  src/app/(common)/mypage/_components/ReviewModal/FormActions.tsx
  src/app/(common)/mypage/_components/ReviewModal/ReviewModal.tsx
  src/app/(common)/mypage/_hooks/useMypageModal.ts
  src/app/(common)/mypage/_hooks/useReviewForm.ts
  src/components/Popup/Popup.tsx
  src/components/ScrollToTop.tsx
Labels: 기능, 리팩토링

#225 fix: 지난 모임일 시 모임 취소 불가
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/app/(common)/reviews/_components/AllReview.tsx
Labels: 기능, 리팩토링

#226 MetaInfoProps의 imageUrl 타입을 인터섹션 타입으로 변경
  src/components/ListItem.tsx
Labels: 리팩토링

#229 마이페이지 - 컴포넌트 분리 및 시멘팅 태그
  src/app/(common)/mypage/_components/MypageContent.tsx
  src/app/(common)/mypage/_components/MypageContentSection.tsx
  src/app/(common)/mypage/_components/MypageTab.tsx
  src/app/(common)/mypage/_components/ReviewModal/CommentInput.tsx
  src/app/(common)/mypage/_components/ReviewModal/ReviewModal.tsx
  src/app/(common)/mypage/utils/apis.ts
Labels: 리팩토링

#230 fix: 모집 정원 초과 시 모달
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/app/(common)/gathering/_hooks/useJoin.ts
Labels: 버그, 리팩토링

#231 마이페이지 - 에러 핸들링 및 staleTime설정
  src/app/(common)/mypage/_components/MypageList.tsx
  src/app/(common)/mypage/_hooks/useMypageModal.ts
  src/app/(common)/mypage/_hooks/usePostReviews.ts
  src/app/(common)/mypage/_hooks/useProfileEditForm.ts
  src/app/(common)/mypage/_hooks/useUpdateUserInfo.ts
  src/app/api/getUser.ts
Labels: 기능, 리팩토링

#232 Fix: 화면 깜빡임 버그 수정, 컴포넌트 분리 및 공용 type 사용
  src/app/(common)/_home/CardList.tsx
  src/app/(common)/_home/_components/GatheringFilters.tsx
  src/app/(common)/_home/_components/GatheringList.tsx
  src/app/(common)/_home/_components/HeaderSection.tsx
  src/app/(common)/_home/_hooks/useFetchGatherings.ts
  src/app/(common)/_home/_hooks/useFilters.ts
  src/app/(common)/favorites/FavoriteList.tsx
  src/types.ts
Labels: 버그, 리팩토링

#234 Fix: 모임 생성 UI, 로직 분리, 달력 UX 개선
  src/app/(common)/_home/_components/CapacityField.tsx
  src/app/(common)/_home/_components/CategorySelectField.tsx
  src/app/(common)/_home/_components/CreateGatheringForm.tsx
  src/app/(common)/_home/_components/CreateGatheringsModal.tsx
  src/app/(common)/_home/_components/ImageUploadFiled.tsx
  src/app/(common)/_home/_components/LocationSelectField.tsx
  src/app/(common)/_home/_components/MeetingDateTimeField.tsx
  src/app/(common)/_home/_components/MeetingDateTimeValidator.tsx
  src/app/(common)/_home/_components/MeetingNameField.tsx
  src/components/Filtering/CustomDatepicker.tsx
  src/components/Filtering/LocationSelect.tsx
  src/stores/useGatheringStore.ts
Labels: 리팩토링

#236 fix: 상세페이지와 모든 리뷰 페이지 코드 정리
  src/app/(common)/gathering/[id]/page.tsx
  src/app/(common)/gathering/_components/GatheringInfo.tsx
  src/app/(common)/gathering/_components/Reviews.tsx
  src/app/(common)/gathering/_utils/constants.ts
  src/app/(common)/gathering/_utils/queryUtils.ts
  src/app/(common)/reviews/_components/AllReview.tsx
  src/app/(common)/reviews/_utils/constants.ts
  src/app/(common)/reviews/page.tsx
  src/hooks/useGetReviews.ts
  src/hooks/useQueryParams.ts
Labels: 리팩토링

#237 fix: utc 기준 현재 날짜 비교
  src/app/(common)/gathering/_components/FloatingBar.tsx
  src/utils/date.ts
Labels: 버그

#238 시간 관련 수정사항
  src/app/(common)/_home/_components/CreateGatheringForm.tsx
  src/app/(common)/_home/_hooks/useGathering.ts
  src/app/(common)/mypage/page.tsx
  src/components/Card.tsx
  src/components/ChipInfo.tsx
  src/components/ListItem.tsx
  src/components/Tag.tsx
  src/utils/date.ts
Labels: 리팩토링

#239 fix: 메인, 찜한 모임에서 progress bar 새로고침 시 적 용 안되는 문제 해결
  src/components/AnimateParticipantCount.tsx
  src/components/Card.tsx
  src/components/ProgressBar.tsx
Labels: 버그

#241 fix: 기본 이미지 변경 및 리뷰 Link 추가
  public/images/default_image.png
  src/app/(common)/reviews/_components/AllReview.tsx
Labels: 리팩토링

#240 fix: 리뷰에서 작성자 프로필 수정
  src/app/(common)/gathering/_components/ReviewList.tsx
  src/app/layout.tsx
Labels: UI

#242 fix: 카드 살짝 걸쳤을 때 무한 호출 버그 수정
  src/app/(common)/_home/_components/GatheringList.tsx
  src/components/Card.tsx
  src/hooks/useInfiniteScroll.ts
Labels: 버그

#244 fix: 리뷰 날짜 데이터 수정(모임날짜 -> 리뷰등록날짜)
  src/app/(common)/reviews/_components/AllReview.tsx
Labels: 버그
